# Generated by Django 3.2 on 2022-03-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
